### ISSUE TITLE
Switchable banner/notification/alert about important security upgrades

### ISSUE THREAD

**Issue by fhemberger** [nodejs/new.nodejs.org#17]
Reminder based on https://github.com/nodejs/iojs.org/issues/397

**Comment by hoxoa** [comment]
@fhemberger I have a working version. Will make a PR for it.

Just a  few things I noticed, 
* shouldn't the css from `index.hbs` go to the css (.styl) 
* the same with the css in `download.hbs` and add the picture to the images folder instead of hardcoding
* why is the mac version hardcoded on the index, maybe a bit strange if you click download on a linux os.

**Comment by fhemberger** [comment]
@hoxoa Yes, all styles are supposed to be in the .styl files, also the hard coding of the Mac version was just a mishap. /cc @mikeal
